default: 
  defaults: 
    shell: "bash -xe"
  server: 
    scheme: http
    hostname: localhost
    port: 8080
  slaves: 
    - id: slave1
      applicability: general
      name: Local Slave 1
      type: local
    - id: slave2
      applicability: general
      name: Local Slave 2
      type: local
    - id: slave3
      applicability: general
      name: Local Slave 3
      type: local
    - id: slave4
      applicability: general
      name: Local Slave 4
      type: local
  campaigns: []
  missions: []
  workspaces: []
